server {
    listen       80;
    listen  [::]:80;
    server_name  bitcoin-block-count;

    charset utf-8;
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;

    add_header  X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    add_header  X-FROM "bitcoin-block-count";

    location / {
        # First attempt to serve request as file, then
        # as directory, then fall back to displaying a 404.
        try_files $uri $uri/ =404;
        root   /usr/share/nginx/html;
        index  index.html;
    }

    error_page  404 /404.html;
    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = / {
        root   /usr/share/nginx/html;
    }

}
